// <auto-generated />
namespace realtime_idea_space.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdeaModelComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdeaModelComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201605071448307_IdeaModel.Comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
